### ISSUE TITLE
Fix global submit

### ISSUE THREAD

**Issue by AndreiCrimezniuc** [AndreiCrimezniuc/AreaSelector#3]
It needs to fix following issue.
1) Check why component SubmitButton doesn't appears 
2) Check if SubmitButton works well(submit all forms from page with class 'selector-form' and handle it in one function and send all fetched data in json to /area

**Comment by AndreiCrimezniuc** [comment]
ah, forget. Already fixed by me

**Comment by IgorCavliuc** [comment]
)
